language: python

python:
  - "3.8"

install:
  - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/wxPython-4.1.0-cp38-cp38-linux_x86_64.whl wxPython
  - pip install --upgrade -r requirements.txt

script:
  - make test
