agents:
  image: jarpy/shakersynth

steps:
  - label: Env
    command: "env | cut -f1 -d= | sort"

  - label: Test
    command: "pip install --editable . && pytest -v"

  - label: Type Check
    command: "mypy ."

  - label: Lint
    command: "flake8"

  - label: Package
    command: "make install"

