agents:
  queue: jarpy

steps:
  - label: Go Choco
    command:
      - powershell.exe -noexit "Set-ExecutionPolicy Bypass -Scope Process -Force"
      - powershell.exe -noexit "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072"
      - powershell.exe -noexit "iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"


